version: 2.1

# jobs definitions
jobs:
  test-and-analysis:
    docker:
      - image: cimg/openjdk:11.0
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn clean test sonar:sonar org.pitest:pitest-maven:mutationCoverage -Dsonar.projectKey=massimostanzione_openjpa --projects .,openjpa-jdbc,openjpa-lib
      - run:
          name: Prepare artifacts (Mutation testing)
          command: |
            mkdir -p /tmp/openjpa-jdbc/pit-reports
            mkdir -p /tmp/openjpa-lib/pit-reports
            cp -r ~/project/openjpa-jdbc/target/pit-reports /tmp/openjpa/opejpa-jdbc/pit-reports
            cp -r ~/project/openjpa-lib/target/pit-reports /tmp/openjpa/opejpa-lib/pit-reports
      - store_artifacts:
          path: /tmp/openjpa/opejpa-jdbc/pit-reports
      - store_artifacts:
          path: /tmp/openjpa/opejpa-lib/pit-reports

# invoking jobs via workflows
workflows:
  main:
    jobs:
      - test-and-analysis:
          context: SonarCloud
